<?php
// Set working directory to project root for all serverless executions
$root_dir = realpath(__DIR__ . '/..') ?: (__DIR__ . '/..');
chdir($root_dir);

// Diagnostic crash handler so Vercel never shows generic 500 FUNCTION_INVOCATION_FAILED
register_shutdown_function(function () {
    $error = error_get_last();
    if ($error && in_array($error['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR, E_USER_ERROR])) {
        http_response_code(500);
        if (!headers_sent()) {
            header('Content-Type: text/html; charset=utf-8');
        }
        echo '<!DOCTYPE html><html><head><title>Cafe Server Diagnostic</title>';
        echo '<style>body { font-family: system-ui, -apple-system, sans-serif; background: #1a1a1a; color: #fff; text-align: center; padding: 50px; }';
        echo 'h1 { color: #d4af37; } .box { background: #2a2a2a; border-radius: 10px; padding: 30px; max-width: 700px; margin: 0 auto; border: 1px solid #ff4d4d; text-align: left; }</style></head><body>';
        echo '<div class="box"><h2 style="color: #ff4d4d; margin-top: 0;">⚠️ Vercel PHP Diagnostic Report</h2>';
        echo '<p style="color: #ffaa00; background: #333; padding: 10px; border-radius: 5px; font-family: monospace; word-break: break-all;">Error: ' . htmlspecialchars($error['message']) . '</p>';
        echo '<p><b>File:</b> <code>' . htmlspecialchars($error['file']) . '</code><br><b>Line:</b> ' . $error['line'] . '</p>';
        echo '<hr style="border-color: #444; margin: 20px 0;"><p style="color: #ccc; font-size: 14px;">This diagnostic report is generated by Owl Cafe to help identify deployment issues on Vercel.</p>';
        echo '</div></body></html>';
    }
});

set_exception_handler(function ($e) {
    http_response_code(500);
    if (!headers_sent()) {
        header('Content-Type: text/html; charset=utf-8');
    }
    echo '<!DOCTYPE html><html><head><title>Cafe Exception Diagnostic</title>';
    echo '<style>body { font-family: system-ui, -apple-system, sans-serif; background: #1a1a1a; color: #fff; text-align: center; padding: 50px; }';
    echo 'h1 { color: #d4af37; } .box { background: #2a2a2a; border-radius: 10px; padding: 30px; max-width: 700px; margin: 0 auto; border: 1px solid #ff4d4d; text-align: left; }</style></head><body>';
    echo '<div class="box"><h2 style="color: #ff4d4d; margin-top: 0;">⚠️ Vercel PHP Exception Report</h2>';
    echo '<p style="color: #ffaa00; background: #333; padding: 10px; border-radius: 5px; font-family: monospace; word-break: break-all;">Exception: ' . htmlspecialchars($e->getMessage()) . '</p>';
    echo '<p><b>File:</b> <code>' . htmlspecialchars($e->getFile()) . '</code><br><b>Line:</b> ' . $e->getLine() . '</p>';
    echo '<hr style="border-color: #444; margin: 20px 0;"><p style="color: #ccc; font-size: 14px;">This diagnostic report is generated by Owl Cafe to help identify deployment issues on Vercel.</p>';
    echo '</div></body></html>';
    exit;
});

$request_uri = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/';

// Remove the base path if necessary, but on Vercel it's usually just /
$file = realpath($root_dir . $request_uri);
$base_dir = $root_dir;

if ($request_uri === '/' || $request_uri === '' || $request_uri === '/index.php' || $request_uri === '/index') {
    chdir($root_dir);
    require $root_dir . '/index.php';
} elseif ($file && strpos($file, $base_dir) === 0 && file_exists($file) && is_file($file)) {
    if (pathinfo($file, PATHINFO_EXTENSION) === 'php') {
        chdir(dirname($file));
        require $file;
    } else {
        // Serve static files if not handled by Vercel routes
        $mime_types = [
            'css' => 'text/css',
            'js' => 'application/javascript',
            'png' => 'image/png',
            'jpg' => 'image/jpeg',
            'jpeg' => 'image/jpeg',
            'gif' => 'image/gif',
            'svg' => 'image/svg+xml'
        ];
        $ext = pathinfo($file, PATHINFO_EXTENSION);
        if (isset($mime_types[$ext])) {
            header('Content-Type: ' . $mime_types[$ext]);
        }
        readfile($file);
    }
} elseif ($file && strpos($file, $base_dir) === 0 && is_dir($file)) {
    if (file_exists($file . '/index.php')) {
        chdir($file);
        require $file . '/index.php';
    } else {
        http_response_code(403);
        echo "403 Forbidden - Directory Access Denied";
    }
} elseif (file_exists($root_dir . $request_uri . '.php')) {
    $target = $root_dir . $request_uri . '.php';
    chdir(dirname($target));
    require $target;
} else {
    http_response_code(404);
    echo "404 Not Found";
}
?>
